# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uis/main_window.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_OnLineEditor(object):
    def setupUi(self, OnLineEditor):
        OnLineEditor.setObjectName("OnLineEditor")
        OnLineEditor.resize(1167, 748)
        self.centralwidget = QtWidgets.QWidget(OnLineEditor)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.le_find = QtWidgets.QLineEdit(self.centralwidget)
        self.le_find.setObjectName("le_find")
        self.horizontalLayout_2.addWidget(self.le_find)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.tw_online = QtWidgets.QTreeView(self.splitter)
        self.tw_online.setEditTriggers(QtWidgets.QAbstractItemView.DoubleClicked)
        self.tw_online.setDragEnabled(True)
        self.tw_online.setDragDropMode(QtWidgets.QAbstractItemView.DragDrop)
        self.tw_online.setDefaultDropAction(QtCore.Qt.MoveAction)
        self.tw_online.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.tw_online.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerItem)
        self.tw_online.setObjectName("tw_online")
        self.tb_device = QtWidgets.QTableView(self.splitter)
        self.tb_device.setEditTriggers(QtWidgets.QAbstractItemView.DoubleClicked)
        self.tb_device.setAlternatingRowColors(False)
        self.tb_device.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tb_device.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tb_device.setObjectName("tb_device")
        self.verticalLayout.addWidget(self.splitter)
        self.fr_device = QtWidgets.QFrame(self.centralwidget)
        self.fr_device.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fr_device.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fr_device.setObjectName("fr_device")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.fr_device)
        self.verticalLayout_2.setContentsMargins(0, -1, 0, -1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.but_edit_properties = QtWidgets.QPushButton(self.fr_device)
        self.but_edit_properties.setObjectName("but_edit_properties")
        self.horizontalLayout_3.addWidget(self.but_edit_properties)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.lb_saved = QtWidgets.QLabel(self.fr_device)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lb_saved.setFont(font)
        self.lb_saved.setObjectName("lb_saved")
        self.horizontalLayout_3.addWidget(self.lb_saved)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.lb_applied = QtWidgets.QLabel(self.fr_device)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lb_applied.setFont(font)
        self.lb_applied.setObjectName("lb_applied")
        self.horizontalLayout_3.addWidget(self.lb_applied)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.but_check = QtWidgets.QPushButton(self.fr_device)
        self.but_check.setObjectName("but_check")
        self.horizontalLayout_3.addWidget(self.but_check)
        self.but_apply = QtWidgets.QPushButton(self.fr_device)
        self.but_apply.setObjectName("but_apply")
        self.horizontalLayout_3.addWidget(self.but_apply)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.verticalLayout.addWidget(self.fr_device)
        OnLineEditor.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(OnLineEditor)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1167, 23))
        self.menubar.setObjectName("menubar")
        OnLineEditor.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(OnLineEditor)
        self.statusbar.setObjectName("statusbar")
        OnLineEditor.setStatusBar(self.statusbar)

        self.retranslateUi(OnLineEditor)
        QtCore.QMetaObject.connectSlotsByName(OnLineEditor)

    def retranslateUi(self, OnLineEditor):
        _translate = QtCore.QCoreApplication.translate
        OnLineEditor.setWindowTitle(_translate("OnLineEditor", "Online.xml Editor"))
        self.label.setText(_translate("OnLineEditor", "Find:"))
        self.but_edit_properties.setText(_translate("OnLineEditor", "Edit device"))
        self.lb_saved.setText(_translate("OnLineEditor", "NOT SAVED"))
        self.lb_applied.setText(_translate("OnLineEditor", "NOT APPLIED"))
        self.but_check.setToolTip(_translate("OnLineEditor", "Checks for error without generation"))
        self.but_check.setText(_translate("OnLineEditor", "Check configuration for errors"))
        self.but_apply.setToolTip(_translate("OnLineEditor", "Generates onlene.xml from the selected configuration"))
        self.but_apply.setText(_translate("OnLineEditor", "Generate ONLINE.XML"))

